#include <iostream>
#include <string>
#include "../include/base64.h"

int main() {
    std::string base64_data = "TgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAAA3AAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAAHAAAABwAAAAcAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAAHAAAABwAAABOAAAATgAAAE4AAABOAAAAHAAAAE4AAABOAAAATgAAAE4AAAAcAAAAHAAAABwAAABOAAAATgAAABwAAABOAAAATgAAAE4AAABOAAAATgAAAE4AAAAcAAAAHAAAABwAAAAcAAAATgAAAE4AAAAcAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAAHAAAABwAAABOAAAATgAAAE4AAABOAAAATgAAABwAAABOAAAATgAAAE4AAAAcAAAAHAAAABwAAAAcAAAAHAAAAE4AAAAcAAAATgAAAA==";

    std::string decoded_data = base64_decode(base64_data);  // 解码函数
    std::cout << decoded_data << std::endl;
    
    return 0;
}